### ISSUE TITLE
`getTargetBlockExact` returning null incorrectly

### ISSUE THREAD

**Issue by Klikini** [BukkitFabric/bukkit4fabric#260]
I am a developer of the Mine Assistant plugin for Bukkit, and I have received a bug report about it not working on Paper via Cardboard. The error returned is caused by the command sender (which must be a player) not having a block targeted.

- [User's bug report](https://gitlab.com/klikini/mineassistant/-/issues/8)
- [Line of code in question](https://gitlab.com/klikini/mineassistant/-/blob/trunk/src/main/java/net/robiotic/mineassistant/MineAssistant.java#L125) (max target distance = 5)

Is there a difference in implementation such that we should check for Cardboard and make the call a different way, or is this a bug?

**Comment by pisaiah** [comment]
Should be fixed now.

**Comment by penguinrepair** [comment]
still crashes silently(including server console error):
Sep 23, 2021 7:36:16 PM net.minecraft.class_3244 handler$zdf000$executeCommand
SEVERE: null
org.bukkit.command.CommandException: Unhandled exception executing command 'hass' in plugin MineAssistant v1.0-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:888)
        at net.minecraft.class_3244.handler$zdf000$executeCommand(class_3244.java:1805)
        at net.minecraft.class_3244.method_14370(class_3244.java)
        at net.minecraft.class_3244.method_31286(class_3244.java:2661)
        at net.minecraft.class_3244.method_12048(class_3244.java:1189)
        at net.minecraft.class_2797.method_12115(class_2797.java:30)
        at net.minecraft.class_2797.method_11054(class_2797.java:7)
        at net.minecraft.class_2600.method_11072(class_2600.java:21)
        at net.minecraft.class_3738.run(class_3738.java:18)
        at net.minecraft.class_1255.method_18859(class_1255.java:151)
        at net.minecraft.class_4093.method_18859(class_4093.java:23)
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788)
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
        at net.minecraft.class_1255.method_16075(class_1255.java:125)
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770)
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764)
        at net.minecraft.class_1255.method_5383(class_1255.java:110)
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:748)
        at net.minecraft.server.MinecraftServer.handler$bac000$modifiedRunLoop(MinecraftServer.java:5899)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_21752()" because "â˜ƒ" is null
        at net.minecraft.class_3727.<init>(class_3727.java:46)
        at net.minecraft.class_3726.method_16195(class_3726.java:16)
        at net.minecraft.class_3959.<init>(class_3959.java:26)
        at org.cardboardpowered.impl.world.WorldImpl.rayTraceBlocks(WorldImpl.java:1155)
        at org.cardboardpowered.impl.entity.LivingEntityImpl.rayTraceBlocks(LivingEntityImpl.java:485)
        at org.cardboardpowered.impl.entity.LivingEntityImpl.getTargetBlockExact(LivingEntityImpl.java:423)
        at org.cardboardpowered.impl.entity.LivingEntityImpl.getTargetBlockExact(LivingEntityImpl.java:418)
        at net.robiotic.mineassistant.MineAssistant.onCommand(MineAssistant.java:125)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
        ... 23 more
