### ISSUE TITLE
Incompatible with CC: Restitched

### ISSUE THREAD

**Issue by Owningle** [BukkitFabric/bukkit4fabric#62]
Crashes when opening a computer.

Mods:
Bukkit4Fabric
Fabric API
CC: Restitched

Plugins:
None

Crash Report: https://pastebin.com/w2jN0mZZ
Server Log: https://pastebin.com/z25kFBGV

**Comment by IsaiahPatton** [comment]
fixed in https://github.com/BukkitFabric/bukkit4fabric/commit/e3870151f23fe3a20643c7c31854046a4735427c

**Comment by Owningle** [comment]
The server no longer crashes, however I am still unable to open the computer, it produces an error in the console when I attempt to do so.

Error: https://pastebin.com/rbs8hn3u
